VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISink"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub OnChange()
End Sub

Public Sub OnListClick()
End Sub

Public Sub OnClick()
End Sub

Public Sub OnDropButtonClick()
End Sub

Public Sub OnDblClick(ByVal Cancel As MSForms.ReturnBoolean)
End Sub

Public Sub OnKeyDown(ByVal KeyCode As MSForms.ReturnInteger, _
                     ByVal Shift As Integer)
End Sub

Public Sub OnKeyUp(ByVal KeyCode As MSForms.ReturnInteger, _
                   ByVal Shift As Integer)
End Sub

Public Sub OnMouseDown(ByVal Button As Integer, _
                       ByVal Shift As Integer, _
                       ByVal X As Single, _
                       ByVal Y As Single)
End Sub

Public Sub OnMouseMove(ByVal Button As Integer, _
                       ByVal Shift As Integer, _
                       ByVal X As Single, _
                       ByVal Y As Single)
End Sub

Public Sub OnMouseUp(ByVal Button As Integer, _
                     ByVal Shift As Integer, _
                     ByVal X As Single, _
                     ByVal Y As Single)
End Sub

Public Sub OnKeyPress(ByVal KeyAscii As MSForms.ReturnInteger)
End Sub

Public Sub OnExit(ByVal Cancel As MSForms.ReturnBoolean)
End Sub

Public Sub OnAfterUpdate()
End Sub

Public Sub OnBeforeUpdate(ByVal Cancel As MSForms.ReturnBoolean)
End Sub

Public Sub OnEnter()
End Sub

Public Sub OnBeforeDragOver(ByVal Cancel As MSForms.ReturnBoolean, _
                            ByVal Data As MSForms.DataObject, _
                            ByVal X As Single, _
                            ByVal Y As Single, _
                            ByVal DragState As MSForms.fmDragState, _
                            ByVal Effect As MSForms.ReturnEffect, _
                            ByVal Shift As Integer)
End Sub

Public Sub OnBeforeDropOrPaste(ByVal Cancel As MSForms.ReturnBoolean, _
                               ByVal Action As MSForms.fmAction, _
                               ByVal Data As MSForms.DataObject, _
                               ByVal X As Single, _
                               ByVal Y As Single, _
                               ByVal Effect As MSForms.ReturnEffect, _
                               ByVal Shift As Integer)
End Sub

Public Sub OnError(ByVal Number As Integer, _
                   ByVal Description As MSForms.ReturnString, _
                   ByVal SCode As Long, ByVal Source As String, _
                   ByVal HelpFile As String, _
                   ByVal HelpContext As Long, _
                   ByVal CancelDisplay As MSForms.ReturnBoolean)
End Sub

'Public Sub OnGotFocus()
'End Sub
'
'Public Sub OnLostFocus()
'End Sub

Public Sub OnAddControl(ByVal Control As MSForms.Control)
End Sub

Public Sub OnLayout()
End Sub

Public Sub OnRemoveControl(ByVal Control As MSForms.Control)
End Sub

Public Sub OnScroll(ByVal ActionX As MSForms.fmScrollAction, _
                    ByVal ActionY As MSForms.fmScrollAction, _
                    ByVal RequestDx As Single, _
                    ByVal RequestDy As Single, _
                    ByVal ActualDx As MSForms.ReturnSingle, _
                    ByVal ActualDy As MSForms.ReturnSingle)
End Sub

'' ScrollBar
'Public Sub OnScroll()
'End Sub

Public Sub OnZoom(Percent As Integer)
End Sub

Public Sub OnSpinDown()
End Sub

Public Sub OnSpinUp()
End Sub

'Public Sub OnMouseOver(ByVal Button As Integer, _
'                       ByVal Shift As Integer)
'End Sub
'
'Public Sub OnMouseOut(ByVal Button As Integer, _
'                       ByVal Shift As Integer)
'End Sub


